// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tAmazonAccount
{
    public string AccountName { get;private set; }

    public string SellerId { get;private set; }

    public string ClientId { get;private set; }

    public string ClientSecret { get;private set; }

    public string RoleArn { get;private set; }

    public int MarketPlaceTypeId { get;private set; }

    public int Id { get; set; }

    public virtual tMarketplaceType MarketPlaceType { get;private set; }
}