// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tAttributeGroup
{
    public int kAttributeGroupId { get;private set; }

    public string sGroupName { get;private set; }
}