// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tAttribute
{
    public int kAttributeId { get;private set; }

    public int? kAttributeGroupId { get;private set; }

    public string sName { get;private set; }

    public virtual ICollection<tAttributeValue> tAttributeValues { get;private set; } = new List<tAttributeValue>();
}