// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tAttributeValue
{
    public int kAttributeValueId { get;private set; }

    public int kAttribueId { get;private set; }

    public int? iValue { get;private set; }

    public string sValue { get;private set; }

    public double? dValue { get;private set; }

    public bool? bValue { get;private set; }

    public string sValueList { get;private set; }

    public virtual tAttribute kAttribue { get;private set; }

    public virtual ICollection<tVariant_Attribute> tVariant_Attributes { get;private set; } = new List<tVariant_Attribute>();
}