// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tCondition
{
    public int kConditionId { get;private set; }

    public string sConditionName { get;private set; }

    public virtual ICollection<tProduct> tProducts { get;private set; } = new List<tProduct>();
}