// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tCustomer
{
    public int kCustomerId { get;private set; }
    public string CustomerName { get; set; }
    public string sCustomerNumber { get;private set; }
    public int? OdooId { get; set; }
    public int? kMarketplaceAccountId { get; private set; }

    public int? kCustomerGroupId { get; private set; }

    public string sMarketplaceAccountName { get; private set; }

    public DateTime? dBirthDate { get; private set; }

    public int? kOdooReference { get; private set; }

    public int? kMarketplaceId { get; private set; }

    public virtual tCustomerGroup kCustomerGroup { get; private set; }

    public virtual ICollection<tCustomerAddress> tCustomerAddresses { get; private set; } = new List<tCustomerAddress>();

    public virtual ICollection<tOrder> tOrders { get; private set; } = new List<tOrder>();
}