// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tCustomerAddress
{
    public int kCustomerAddressId { get; private set; }

    public int? kCustomerId { get; private set; }

    public int? iAddressType { get; private set; }

    public string sCompanyName { get; private set; }

    public string sCompanyAddition { get; private set; }

    public string sSalutation { get; private set; }

    public string sTitle { get; private set; }

    public string sForename { get; private set; }

    public string sSurname { get; private set; }

    public string sStreetAndHousenumber { get; private set; }

    public string sAddressAddition { get; private set; }

    public string sZipCode { get; private set; }

    public string sCity { get; private set; }

    public string sCountry { get; private set; }

    public string sState { get; private set; }

    public string sEmailAddress { get; private set; }

    public string sPhoneNumber { get; private set; }

    public string sMobilePhoneNumber { get; private set; }

    public string sFaxNumber { get; private set; }

    public string sWebsite { get; private set; }

    public virtual tCustomer kCustomer { get; private set; }

    public virtual ICollection<tOrder> tOrders { get; private set; } = new List<tOrder>();
}