// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tEbayAccount
{
    public string AccessToken { get; set; }

    public string RefreshToken { get; set; }

    public TimeOnly? TokenExpiry { get; set; }

    public TimeOnly? LastSyncProducts { get; set; }

    public TimeOnly? LastSyncOrders { get; set; }

    public TimeOnly? LastSyncShipments { get; set; }

    public DateTimeOffset? CreatedAt { get; set; }

    public int MarketplaceTypeId { get; set; }

    public int Id { get; set; }

    public string AccountName { get; set; }

    public string ClientId { get; set; }

    public string ClientSecret { get; set; }

    public string UserId { get; set; }

    public string Environment { get; set; }

    public bool IsActive { get; set; }

    public DateTimeOffset? RefreshTokenExpiresAt { get; set; }

    public DateTimeOffset? AccessTokenExpiresAt { get; set; }

    public DateTimeOffset? UpdatedAt { get; set; }

    public virtual tMarketplaceType MarketplaceType { get; set; }
}