// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tKauflandAccount
{
    public int Id { get; private set; }

    public DateTime? CreatedAt { get; private set; }

    public int MarketPlaceTypeId { get; private set; }

    public string AccountName { get; private set; }

    public string ClientId { get; private set; }

    public string ClientSecret { get; private set; }

    public virtual tMarketplaceType MarketPlaceType { get; private set; }
}