// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tLanguage
{
    public int kLanguageId { get;private set; }

    public string sName { get;private set; }

    public string sIsoCode { get;private set; }

    public virtual ICollection<tProductDescription> tProductDescriptions { get;private set; } = new List<tProductDescription>();
}