// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tLogEntry
{
    public DateTime? dTimestamp { get;private set; }

    public string sMessage { get;private set; }

    public int? kLogLevelId { get;private set; }

    public int? kLogTypeId { get; private set; }

    public virtual tLogLevel kLogLevel { get;private set; }

    public virtual tLogType kLogType { get;private set; }
}