// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tLogType
{
    public int kLogTypeId { get; private set; }

    public string sName { get; private set; }
}