// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tManufacturer
{
    public int kManufacturerId { get; private set; }

    public string sName { get; private set; }

    public string sAddress { get; private set; }

    public string sContactPerson { get; private set; }

    public virtual ICollection<tProduct> tProducts { get; private set; } = new List<tProduct>();
}