// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Entities;
using Domain.Entities.Data;
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tMarketplaceType
{
    public int kMarketplaceType { get; private set; }

    public string sName { get; private set; }

    public virtual ICollection<tAmazonAccount> tAmazonAccounts { get; private set; } = new List<tAmazonAccount>();

    public virtual ICollection<tKauflandAccount> tKauflandAccounts { get; private set; } = new List<tKauflandAccount>();
    public virtual ICollection<tProductMarketplace> ProductMarketplaces { get; private set; } = new List<tProductMarketplace>();
    public virtual ICollection<tOdooAccount> tOdooAccounts { get; private set; } = new List<tOdooAccount>();
    public virtual ICollection<tEbayAccount> tEbayAccounts { get; private set; } = new List<tEbayAccount>();
    public virtual ICollection<tOttoAccount> tOttoAccounts { get; private set; } = new List<tOttoAccount>();
    public virtual ICollection<tShopifyAccount> tShopifyAccounts { get; private set; } = new List<tShopifyAccount>();
}