// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tOdooAccount
{
    public string URL { get; private set; }

    public string DataBaseName { get; private set; }

    public string UserName { get; private set; }

    public string Password { get; private set; }

    public int kMarketplaceTypeId { get; private set; }

    public int Id { get; private set; }

    public string AccountName { get; private set; }

    public bool? SyncProducts { get; private set; }

    public bool? SyncCustomers { get; private set; }

    public bool? SyncSuppliers { get; private set; }

    public bool? SyncOrders { get; private set; }

    public virtual tMarketplaceType kMarketplaceType { get; private set; }
}