// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tOrder
{
    public int kOrderId { get; private set; }

    public string sOrderNumber { get; private set; }

    public int? iOrderStatus { get; private set; }


    public int? kMarketplaceAccountId { get; private set; }

    public int kCustomerId { get; private set; }

    public string sCustomerHint { get; private set; }

    public string sInternalHint { get; private set; }

    public int? kPaymentMethodId { get; private set; }

    public DateTime? dCreationTime { get; private set; }

    public DateTime? dShippingTime { get; private set; }

    public int? kOdooReference { get; private set; }

    public int? kMarketplaceId { get; private set; }

    public int? kOrderAddressId { get; private set; }

    public int? OrderResponseStatus { get; private set; }

    public string OrdersEdiMessage { get; private set; }

    public virtual tCustomer kCustomer { get; private set; }

    public virtual tCustomerAddress kOrderAddress { get; private set; }

    public virtual tPaymentMethod kPaymentMethod { get; private set; }

    public virtual ICollection<tOrderPosition> tOrderPositions { get; private set; } = new List<tOrderPosition>();

    public virtual ICollection<tShippingPackage> tShippingPackages { get; private set; } = new List<tShippingPackage>();
}