// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tOrderPosition
{
    public int kOrderPositionId { get; private set; }

    public int kOrderId { get; private set; }

    public int? iOrderPositionType { get; private set; }

    public string sName { get; private set; }

    public int kVariantId { get; private set; }

    public double? dNetPrice { get; private set; }

    public double? dVat { get; private set; }

    public int? iQuantity { get; private set; }

    public int? iQuantityShipped { get; private set; }

    public string sPositionHint { get; private set; }

    public virtual tOrder kOrder { get; private set; }

    public virtual tProductVariant kVariant { get; private set; }
}