// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tOttoAccount
{
    public string AccessToken { get; private set; }

    public string RefreshToken { get; private set; }

    public DateTime? TokenExpiry { get; private set; }

    public string ClientEmail { get; private set; }

    public DateTime? LastSyncProducts { get; private set; }

    public DateTime LastSyncOrders { get; private set; }

    public DateTime? LastSyncShipments { get; private set; }

    public DateTime? CreatedAt { get; private set; }

    public string ClientId { get; private set; }

    public string ClientSecret { get; private set; }

    public int kMarketplaceId { get; private set; }

    public string AccountName { get; private set; }

    public int Id { get; private set; }

    public virtual tMarketplaceType kMarketplace { get; private set; }
}