// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tProductImageMapping
{
    public int kProductImageMappingId { get; private set; }

    public int? kProductImageId { get; private set; }

    public int? kProductId { get; private set; }

    public virtual tProductImage kProductImage { get; private set; }
    public virtual tProduct TProduct { get; private set; }
}