// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tProductStock
{
    public int kProductStockId { get; private set; }

    public int? iStockAvailable { get; private set; }

    public int? iStockInOrders { get; private set; }

    public int? iStockInDelivery { get; private set; }

    public int? kWarehouseId { get; private set; }

    public int? kOdooReference { get; private set; }

    public int kProductVariantId { get; private set; }

    public virtual tProductVariant kProductVariant { get; private set; }
}