// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tProductImage
{
    public int kProductImageId { get;private set; }

    public string sImage { get; private set; }

    public int? iNumber { get; private set; }

    public virtual ICollection<tProductImageMapping> tProductImageMappings { get; private set; } = new List<tProductImageMapping>();
}