// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tProductDescription
{
    public int kProductDescriptionId { get;private set; }

    public int? kLanguageId { get; private set; }

    public int? kProductId { get; private set; }

    public string sShortDescription { get; private set; }

    public string sDescription { get; private set; }

    public virtual tLanguage kLanguage { get; private set; }
}