// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tProductCategory
{
    public int kProductCategoryId { get; private set; }

    public string sName { get; private set; }

    public int? kUpperCategoryId { get; private set; }

    public int? kOdooReference { get; private set; }

    public virtual ICollection<tProductCategory> InversekUpperCategory { get; private set; } = new List<tProductCategory>();

    public virtual tProductCategory kUpperCategory { get; private set; }

    public virtual ICollection<tProduct> tProducts { get; private set; } = new List<tProduct>();
}