// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tProductAttributeMapping
{
    public int kProductAttributeMappingId { get;private set; }

    public int? kAttributeValueId { get; private set; }

    public int? kProductId { get; private set; }

    public int? iValuteType { get; private set; }

    public tProduct tProduct { get; private set; }
    public tAttributeValue tAttributeValue { get; private set; }

}