// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Entities.Data;
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tProduct
{
    public int kProductId { get; private set; }

    public bool? bAvailableInOdoo { get; private set; }

    public int? kOdooReference { get; private set; }

    public string sSku { get; private set; }

    public string sName { get; private set; }

    public double? dNetprice { get; private set; }

    public int? kVatTypeId { get; private set; }

    public bool? bEnabled { get; private set; }

    public bool? bStockEnabled { get; private set; }

    public double? dPackedWeight { get; private set; }

    public double? dLength { get; private set; }

    public double? dWidth { get; private set; }

    public double? dWeight { get; private set; }

    public int? iHandlingTime { get; private set; }

    public int? kConditionId { get; private set; }

    public string sGTIN { get; private set; }

    public string sMPN { get; private set; }

    public string sASIN { get; private set; }

    public string sISBN { get; private set; }

    public string sUPC { get; private set; }

    public string sOriginCountry { get; private set; }

    public string sTaricCode { get; private set; }

    public int? kManufacturerId { get; private set; }

    public int? kSupplierId { get; private set; }

    public int? kResponsiblePersonGPSRId { get; private set; }

    public int? kSalesChannelProductMappingId { get; private set; }

    public int? CategoryId { get; private set; }

    public int kMarketplaceAccountId { get; private set; }

    public string kProductCode { get; private set; }

    public int kMarketplaceId { get; private set; }

    public virtual tProductCategory Category { get; private set; }

    public virtual tCondition kCondition { get; private set; }

    public virtual tManufacturer kManufacturer { get; private set; }

    public virtual tResponsiblePersonGPSR kResponsiblePersonGPSR { get; private set; }

    public virtual tSalesChannelProductMapping kSalesChannelProductMapping { get; private set; }

    public virtual tSupplier kSupplier { get; private set; }

    public virtual tVatType kVatTypeNavigation { get; private set; }
    public ICollection<tProductAttributeMapping> AttributeMappings { get; private set; }
    public virtual ICollection<tProductMarketplace> ProductMarketplaces { get; private set; } = new List<tProductMarketplace>();

    public virtual ICollection<tProductVariant> tProductVariants { get; private set; } = new List<tProductVariant>();
}