// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Entities;
using Domain.Entities.Data;
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tProductVariant
{
    public string Name { get; private set; }

    public int Id { get; private set; }

    public string SKU { get; private set; }

    public string Barcode { get; private set; }

    public decimal Price { get; private set; }

    public int Quantity { get; private set; }

    public string Image { get; private set; }

    public int Product_Id { get; private set; }

    public int? OdooId { get; private set; }

    public double? Weight { get; private set; }

    public double? Width { get; private set; }

    public double? Length { get; private set; }

    public double? PackedWeight { get; private set; }

    public double? PackedLength { get; private set; }

    public double? PackedWidth { get; private set; }

    public virtual tProduct Product { get; private set; }

    public virtual ICollection<tOrderPosition> tOrderPositions { get; private set; } = new List<tOrderPosition>();

    public virtual ICollection<tProductStock> tProductStocks { get; private set; } = new List<tProductStock>();
    public virtual ICollection<tVariant_Attribute> tVariant_Attributes { get; private set; } = new List<tVariant_Attribute>();


}