// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tResponsiblePersonGPSR
{
    public int kResponsiblePersonGPSRId { get; private set; }

    public string sCompanyName { get; private set; }

    public string sCompanyNameAddition { get; private set; }

    public string sSalutation { get; private set; }

    public string sTitle { get; private set; }

    public string sForename { get; private set; }

    public string sSurename { get; private set; }

    public string sStreet { get; private set; }

    public string sHousenumber { get; private set; }

    public string sAdressAddition { get; private set; }

    public string sZipCode { get; private set; }

    public string sCity { get; private set; }

    public string sCountry { get; private set; }

    public string sState { get; private set; }

    public string sPhonenumber { get; private set; }

    public string sMobilephonenumber { get; private set; }

    public string sFaxnumber { get; private set; }

    public string sEmailAddress { get; private set; }

    public string sWebsite { get; private set; }

    public virtual ICollection<tProduct> tProducts { get; private set; } = new List<tProduct>();
}