// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tSalesChannelProductMapping
{
    public int kSalesChannelProductMappingId { get;private  set; }

    public int? kMarketplaceId { get; private set; }

    public bool? bEnabled { get; private set; }

    public int? iSurchargeType { get; private set; }

    public double? dSurchargeAmount { get; private set; }

    public virtual ICollection<tProduct> tProducts { get; private set; } = new List<tProduct>();
}