// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tShippingPackage
{
    public int kShippingPackageId { get; private set; }

    public int? kShippingMethodId { get; private set; }

    public int? kOrderId { get; private set; }

    public string sTrackingNumber { get; private set; }

    public double? dPackageWeight { get; private set; }

    public DateTime? dCreationTime { get; private set; }

    public virtual tOrder kOrder { get; private set; }

    public virtual tShippingMethod kShippingMethod { get; private set; }
}