// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tShippingMethod
{
    public int kShippingMethodId { get; private set; }

    public string sName { get; private set; }

    public double? dPrice { get; private set; }

    public virtual ICollection<tShippingPackage> tShippingPackages { get; private set; } = new List<tShippingPackage>();
}