// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tShopifyAccount
{
    public int Id { get; private set; }

    public string AccountName { get; private set; }

    public string ApiToken { get; private set; }

    public string StoreName { get; private set; }

    public int MarketplaceTypeId { get; private set; }

    public virtual tMarketplaceType MarketplaceType { get; private set; }
}