// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tSupplier
{
    public int kSupplierId { get; private set; }

    public string sName { get; private set; }

    public int? iSupplierStock { get; private set; }

    public double? dSupplierPrice { get; private set; }

    public int? iMinPurchaseQuantity { get; private set; }

    public int? kOdooReference { get; private set; }

    public virtual ICollection<tProduct> tProducts { get; private set; } = new List<tProduct>();
}