// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tVariant_Attribute
{
    public int id { get; private set; }

    public int variant_id { get; private set; }

    public int AttributeValueId { get; private set; }

    public virtual tAttributeValue AttributeValue { get; private set; }

    public virtual tProductVariant variant { get; private set; }
}