// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoreSystem.DAL.Context.Models;

public partial class tVatType
{
    public int kVatType { get; private set; }

    public string sVatName { get; private set; }

    public double? dAmount { get; private set; }

    public virtual ICollection<tProduct> tProducts { get; private set; } = new List<tProduct>();
}